version: "3.3"

services:

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.whoami.rule=Host(`whoami.cthylla.codes`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.middlewares.whoami.redirectscheme.scheme=https"
      - "traefik.http.middlewares.whoami.redirectscheme.permanent=true"

networks:
  default:
    external:
      name: traefik_default
