version: '3.7'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      pgnet:
        ipv4_address: ${POSTGRES_IP}

  adminer:
    image: adminer
    networks:
      pgnet:
        ipv4_address: ${ADMINER_IP}

volumes:
  postgres:

networks:
  pgnet:
    ipam:
      config:
        - subnet: ${SUBNET}