http:
  routers:
    http-traefik:
      rule: "Host(`traefik.cthylla.codes`)"
      service: "traefik"
      middlewares:
        - "redirect"

    https-traefik:
      rule: "Host(`traefik.cthylla.codes`)"
      service: "traefik"
      tls: {} 

  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8080

  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true


tls:
  certificates:
    - certFile: "/etc/certs/fullchain.pem"
      keyFile: "/etc/certs/privkey.pem"
