version: '3.7'

services:
  db:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - mongo:/data/db
    networks:
      mongonet:
        ipv4_address: ${MONGO_IP}

volumes:
  mongo:

networks:
  mongonet:
    ipam:
      config:
        - subnet: ${SUBNET}
